version: '3'
services:
  app:
    build: .
    image: layosh-test:2.0.3
    volumes:
      - ./attachments:/app/attachments
      - ./config:/app/config
      - ./data:/app/data
    working_dir: /app
    command: python src/main.py